/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.fileshare;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int folder=0x7f020000;
    }
    public static final class id {
        public static final int addfile=0x7f050005;
        public static final int cancel_button=0x7f050002;
        public static final int foldername=0x7f050000;
        public static final int foldersize=0x7f050003;
        public static final int help=0x7f050004;
        public static final int manage=0x7f050006;
        public static final int ok_button=0x7f050001;
        public static final int sharefile_port=0x7f050008;
        public static final int sharefile_progress=0x7f050009;
        public static final int url=0x7f050007;
    }
    public static final class layout {
        public static final int createfolder=0x7f030000;
        public static final int deletefolder=0x7f030001;
        public static final int help=0x7f030002;
        public static final int main=0x7f030003;
        public static final int progress=0x7f030004;
    }
    public static final class string {
        public static final int addfile_button=0x7f040002;
        public static final int app_name=0x7f040000;
        public static final int choosefile_title=0x7f040003;
        public static final int create=0x7f04000b;
        public static final int create_cancel_button=0x7f04000d;
        public static final int create_ok_button=0x7f04000c;
        public static final int delete=0x7f040006;
        public static final int delete_cancel_button=0x7f04000a;
        public static final int delete_ok_button=0x7f040009;
        public static final int edit=0x7f04000e;
        public static final int empty_directory=0x7f040004;
        public static final int foldername_prefix=0x7f040007;
        public static final int foldersize_prefix=0x7f040008;
        public static final int help_button=0x7f040013;
        public static final int help_content=0x7f040014;
        public static final int ipaddress_prefix=0x7f04000f;
        public static final int manage_button=0x7f040001;
        public static final int port=0x7f040005;
        public static final int port_prefix=0x7f040010;
        public static final int unknown_ipaddress=0x7f040012;
        public static final int url_prefix=0x7f040011;
    }
}
